version: '3.8'

services:

  angular-app:

    build:

      context: .

      dockerfile: Dockerfile.dev

    ports:

      - "4200:4200"

    environment:
      - NG_ALLOWED_HOSTS=localhost

    volumes:

      - .:/app

      - /app/node_modules