# -------------------------
# Apache2 Deployment
# -------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80

---
# -------------------------
# Apache2 Service
# -------------------------
apiVersion: v1
kind: Service
metadata:
  name: apache-server
spec:
  type: NodePort
  selector:
    app: apache-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081