apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservice-app
type: Opaque
data:
  # admin / password / my-super-secret-jwt-key
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWp3dC1rZXk=
