pipeline {
    agent none

    stages {

        stage('Checkout') {
            agent {
                label 'compile-node'
            }

            steps {
                echo "Checkout running on ${env.NODE_NAME}"

                deleteDir()

                git branch: 'Devops_LabL1_2023-27',
                    url: 'https://github.com/aditisharmas11/Devops-Lab-L1_2023-27.git'
            }
        }

        stage('Compile') {
            agent {
                label 'compile-node'
            }

            steps {
                echo "Compile running on ${env.NODE_NAME}"

                dir('23070122091_DhruvGangurde/Project4/Project4_Jenkins_Scale/maven-project') {

                    bat '''
                        set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-21.0.11.10-hotspot"
                        set "PATH=%JAVA_HOME%\bin;%PATH%"

                        echo ===== JAVA VERSION =====
                        java -version

                        echo ===== MAVEN VERSION =====
                        mvn -version

                        echo ===== MAVEN COMPILE =====
                        mvn clean compile
                    '''
                }
            }
        }

        stage('Test') {
            agent {
                label 'test-node'
            }

            steps {
                echo "Test running on ${env.NODE_NAME}"

                deleteDir()

                git branch: 'Devops_LabL1_2023-27',
                    url: 'https://github.com/aditisharmas11/Devops-Lab-L1_2023-27.git'

                dir('23070122091_DhruvGangurde/Project4/Project4_Jenkins_Scale/maven-project') {

                    bat '''
                        set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-21.0.11.10-hotspot"
                        set "PATH=%JAVA_HOME%\bin;%PATH%"

                        echo ===== JAVA VERSION =====
                        java -version

                        echo ===== MAVEN VERSION =====
                        mvn -version

                        echo ===== MAVEN TEST =====
                        mvn test
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "========================================="
            echo "DISTRIBUTED MAVEN PIPELINE SUCCESSFUL"
            echo "Compile Node and Test Node completed."
            echo "========================================="
        }

        failure {
            echo "DISTRIBUTED MAVEN PIPELINE FAILED"
        }
    }
}