apiVersion: v1
kind: Service
metadata:
  name: socialsphere-frontend
  namespace: socialsphere
spec:
  selector:
    app: socialsphere-frontend

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: NodePort