apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project8
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 31781
    targetPort: 31781
    nodePort: 31781
    protocol: TCP
  selector:
    app: frontend
